### ISSUE TITLE
config.php

### ISSUE THREAD

**Issue by irrg** [ericbae/XTA2#1]
Just curious, but why are you tacking onto config.php instead of adding, say, xta2.php to the config folder? 

I'm integrating your new version of XTA (might want to mention XTA2 on that repository) and I'm having a hard time seeing which files are changed and which are not, in general.

**Comment by ericbae** [comment]
Hi @irrg.

Hm. The answer to your first question is "why not" ? :) There is no problem for you to move the settings that I have put in there to another config file called xta2.php as you suggested. It will work just the same. I guess there weren't too many additional things, so I just threw them in there. But you are more than welcome to move it to another file to suit your need.

In regards to the difference between XTA and XTA2, if I wanted to do the work of XTA2 on TOP of XTA, I would have. But I just wanted to create a new repo and start afresh. Hence the reason why I it's a brand new project. If you are trying to diff between the two, well the answer is "there are lots of changes".

I did mention XTA2 on XTA WIKI, but you're right, I guess I should mention it more obviously on XTA project.
